from PyQt5.QtWidgets import QGridLayout, QLabel, QLineEdit, QTextEdit


class demirbas_detay(QGridLayout):
    def __init__(self):
        super().__init__()
        self.demirbas_no_label = QLabel("Demirbaş No")
        self.urun_adi_label = QLabel("Ürün Adı")
        self.teslim_alan_label = QLabel("Teslim Alan")
        self.islem_tarihi_label = QLabel("İşlem Tarihi")
        self.kategori_label = QLabel("Kategori")
        self.adet_label = QLabel("Ürün Adeti")
        self.marka_label = QLabel("Marka")
        self.model_label = QLabel("Model")
        self.seri_no_label = QLabel("Seri No")
        self.garanti_suresi_label = QLabel("Garanti Süresi")
        self.satin_alinma_tarihi_label = QLabel("Satın Alınma Tarihi")
        self.bulundugu_yer_label = QLabel("Bulunduğu Yer")
        self.aciklama_label = QLabel("Açıklama")

        self.addWidget(self.demirbas_no_label, 0, 0)
        self.addWidget(self.urun_adi_label, 1, 0)
        self.addWidget(self.teslim_alan_label, 2, 0)
        self.addWidget(self.islem_tarihi_label, 3, 0)
        self.addWidget(self.kategori_label, 4, 0)
        self.addWidget(self.adet_label, 5, 0)
        self.addWidget(self.marka_label, 6, 0)
        self.addWidget(self.model_label, 7, 0)
        self.addWidget(self.seri_no_label, 8, 0)
        self.addWidget(self.garanti_suresi_label, 9, 0)
        self.addWidget(self.satin_alinma_tarihi_label, 10, 0)
        self.addWidget(self.bulundugu_yer_label, 11, 0)
        self.addWidget(self.aciklama_label, 12, 0)

        self.demirbas_no = QLineEdit()
        self.urun_adi = QLineEdit()
        self.teslim_alan = QLineEdit()
        self.islem_tarihi = QLineEdit()
        self.kategori = QLineEdit()
        self.adet = QLineEdit()
        self.marka = QLineEdit()
        self.model = QLineEdit()
        self.seri_no = QLineEdit()
        self.garanti_suresi = QLineEdit()
        self.satin_alinma_tarihi = QLineEdit()
        self.bulundugu_yer = QLineEdit()
        self.aciklama = QTextEdit()

        self.demirbas_no.setDisabled(True)
        self.urun_adi.setDisabled(True)
        self.teslim_alan.setDisabled(True)
        self.islem_tarihi.setDisabled(True)
        self.kategori.setDisabled(True)
        self.adet.setDisabled(True)
        self.marka.setDisabled(True)
        self.model.setDisabled(True)
        self.seri_no.setDisabled(True)
        self.garanti_suresi.setDisabled(True)
        self.satin_alinma_tarihi.setDisabled(True)
        self.bulundugu_yer.setDisabled(True)
        self.aciklama.setDisabled(True)

        self.addWidget(self.demirbas_no, 0, 1)
        self.addWidget(self.urun_adi, 1, 1)
        self.addWidget(self.teslim_alan, 2, 1)
        self.addWidget(self.islem_tarihi, 3, 1)
        self.addWidget(self.kategori, 4, 1)
        self.addWidget(self.adet, 5, 1)
        self.addWidget(self.marka, 6, 1)
        self.addWidget(self.model, 7, 1)
        self.addWidget(self.seri_no, 8, 1)
        self.addWidget(self.garanti_suresi, 9, 1)
        self.addWidget(self.satin_alinma_tarihi, 10, 1)
        self.addWidget(self.bulundugu_yer, 11, 1)
        self.addWidget(self.aciklama, 12, 1)



    def veri_yukle(self, lst):
        self.demirbas_no.setText(str(lst[1]))
        self.urun_adi.setText(lst[2])
        self.teslim_alan.setText(lst[3])
        self.islem_tarihi.setText(lst[4])
        self.kategori.setText(lst[5])
        self.adet.setText(str(lst[6]))
        self.marka.setText(lst[7])
        self.model.setText(lst[8])
        self.seri_no.setText(lst[9])
        self.garanti_suresi.setText(str(lst[10]))
        self.satin_alinma_tarihi.setText(lst[11])
        self.bulundugu_yer.setText(lst[12])
        self.aciklama.setText(lst[13])
